# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'walk_pattern.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QLabel, QMainWindow,
    QMenuBar, QPushButton, QRadioButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(958, 603)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(330, 20, 300, 30))
        font = QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, 80, 100, 30))
        font1 = QFont()
        font1.setPointSize(12)
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(660, 80, 100, 30))
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(340, 390, 100, 30))
        self.label_4.setFont(font1)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(340, 445, 100, 30))
        self.label_5.setFont(font1)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(340, 500, 100, 30))
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox_step = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_step.setObjectName(u"doubleSpinBox_step")
        self.doubleSpinBox_step.setGeometry(QRect(450, 390, 120, 40))
        self.doubleSpinBox_step.setMinimum(0.000000000000000)
        self.doubleSpinBox_step.setMaximum(20.000000000000000)
        self.doubleSpinBox_step.setSingleStep(0.100000000000000)
        self.doubleSpinBox_step.setValue(1.000000000000000)
        self.doubleSpinBox_swing = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_swing.setObjectName(u"doubleSpinBox_swing")
        self.doubleSpinBox_swing.setGeometry(QRect(450, 445, 120, 40))
        self.doubleSpinBox_swing.setMinimum(0.000000000000000)
        self.doubleSpinBox_swing.setMaximum(20.000000000000000)
        self.doubleSpinBox_swing.setSingleStep(0.100000000000000)
        self.doubleSpinBox_swing.setValue(1.000000000000000)
        self.doubleSpinBox_rise = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_rise.setObjectName(u"doubleSpinBox_rise")
        self.doubleSpinBox_rise.setGeometry(QRect(450, 500, 120, 40))
        self.doubleSpinBox_rise.setMinimum(0.000000000000000)
        self.doubleSpinBox_rise.setMaximum(20.000000000000000)
        self.doubleSpinBox_rise.setSingleStep(0.100000000000000)
        self.doubleSpinBox_rise.setValue(1.000000000000000)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 450, 60, 30))
        self.label_7.setFont(font1)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_view_front = QPushButton(self.centralwidget)
        self.btn_view_front.setObjectName(u"btn_view_front")
        self.btn_view_front.setGeometry(QRect(100, 390, 90, 70))
        self.btn_view_front.setFont(font1)
        self.btn_view_side = QPushButton(self.centralwidget)
        self.btn_view_side.setObjectName(u"btn_view_side")
        self.btn_view_side.setGeometry(QRect(200, 390, 90, 70))
        self.btn_view_side.setFont(font1)
        self.btn_view_top = QPushButton(self.centralwidget)
        self.btn_view_top.setObjectName(u"btn_view_top")
        self.btn_view_top.setGeometry(QRect(100, 470, 90, 70))
        self.btn_view_top.setFont(font1)
        self.btn_walk_on = QPushButton(self.centralwidget)
        self.btn_walk_on.setObjectName(u"btn_walk_on")
        self.btn_walk_on.setGeometry(QRect(790, 390, 120, 70))
        self.btn_walk_on.setFont(font1)
        self.btn_walk_stop = QPushButton(self.centralwidget)
        self.btn_walk_stop.setObjectName(u"btn_walk_stop")
        self.btn_walk_stop.setGeometry(QRect(790, 470, 120, 70))
        self.btn_walk_stop.setFont(font1)
        self.widget_right = QWidget(self.centralwidget)
        self.widget_right.setObjectName(u"widget_right")
        self.widget_right.setGeometry(QRect(20, 120, 450, 250))
        self.widget_right.setAutoFillBackground(True)
        self.widget_right.setStyleSheet(u"")
        self.widget_left = QWidget(self.centralwidget)
        self.widget_left.setObjectName(u"widget_left")
        self.widget_left.setGeometry(QRect(490, 120, 450, 250))
        self.widget_left.setAutoFillBackground(True)
        self.btn_init = QPushButton(self.centralwidget)
        self.btn_init.setObjectName(u"btn_init")
        self.btn_init.setGeometry(QRect(640, 390, 120, 70))
        self.btn_init.setFont(font1)
        self.btn_view_home = QPushButton(self.centralwidget)
        self.btn_view_home.setObjectName(u"btn_view_home")
        self.btn_view_home.setGeometry(QRect(200, 470, 90, 70))
        self.btn_view_home.setFont(font1)
        self.radioButton_both = QRadioButton(self.centralwidget)
        self.radioButton_both.setObjectName(u"radioButton_both")
        self.radioButton_both.setGeometry(QRect(650, 480, 98, 24))
        self.radioButton_both.setChecked(True)
        self.radioButton_one = QRadioButton(self.centralwidget)
        self.radioButton_one.setObjectName(u"radioButton_one")
        self.radioButton_one.setGeometry(QRect(650, 510, 98, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 958, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Walk_Pattern Simulation", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Right Leg", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Left Leg", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Step(mm)", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Swing(mm)", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Rise(mm)", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"View", None))
        self.btn_view_front.setText(QCoreApplication.translate("MainWindow", u"Front", None))
        self.btn_view_side.setText(QCoreApplication.translate("MainWindow", u"Side", None))
        self.btn_view_top.setText(QCoreApplication.translate("MainWindow", u"Top", None))
        self.btn_walk_on.setText(QCoreApplication.translate("MainWindow", u"Walk_On", None))
        self.btn_walk_stop.setText(QCoreApplication.translate("MainWindow", u"Walk_Stop", None))
        self.btn_init.setText(QCoreApplication.translate("MainWindow", u"Init", None))
        self.btn_view_home.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.radioButton_both.setText(QCoreApplication.translate("MainWindow", u"Both Legs", None))
        self.radioButton_one.setText(QCoreApplication.translate("MainWindow", u"One Leg(R)", None))
    # retranslateUi

