# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'axis_2.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(600, 473)
        self.Btn_FK = QPushButton(Form)
        self.Btn_FK.setObjectName(u"Btn_FK")
        self.Btn_FK.setGeometry(QRect(320, 80, 230, 101))
        font = QFont()
        font.setPointSize(15)
        self.Btn_FK.setFont(font)
        self.Btn_FK.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(160, 20, 250, 50))
        font1 = QFont()
        font1.setPointSize(20)
        self.label.setFont(font1)
        self.label.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 70, 130, 50))
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 130, 130, 50))
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 200, 130, 50))
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 260, 130, 50))
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Btn_IK = QPushButton(Form)
        self.Btn_IK.setObjectName(u"Btn_IK")
        self.Btn_IK.setGeometry(QRect(320, 210, 230, 100))
        self.Btn_IK.setFont(font)
        self.Btn_IK.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 330, 130, 50))
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 390, 130, 50))
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Btn_Pattern = QPushButton(Form)
        self.Btn_Pattern.setObjectName(u"Btn_Pattern")
        self.Btn_Pattern.setGeometry(QRect(320, 340, 230, 100))
        self.Btn_Pattern.setFont(font)
        self.Btn_Pattern.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_theta1 = QLineEdit(Form)
        self.lineEdit_theta1.setObjectName(u"lineEdit_theta1")
        self.lineEdit_theta1.setGeometry(QRect(150, 80, 150, 40))
        font2 = QFont()
        font2.setPointSize(12)
        self.lineEdit_theta1.setFont(font2)
        self.lineEdit_theta1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_theta2 = QLineEdit(Form)
        self.lineEdit_theta2.setObjectName(u"lineEdit_theta2")
        self.lineEdit_theta2.setGeometry(QRect(150, 140, 150, 40))
        self.lineEdit_theta2.setFont(font2)
        self.lineEdit_theta2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_x_coordi = QLineEdit(Form)
        self.lineEdit_x_coordi.setObjectName(u"lineEdit_x_coordi")
        self.lineEdit_x_coordi.setGeometry(QRect(150, 210, 150, 40))
        self.lineEdit_x_coordi.setFont(font2)
        self.lineEdit_x_coordi.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_y_coordi = QLineEdit(Form)
        self.lineEdit_y_coordi.setObjectName(u"lineEdit_y_coordi")
        self.lineEdit_y_coordi.setGeometry(QRect(150, 270, 150, 40))
        self.lineEdit_y_coordi.setFont(font2)
        self.lineEdit_y_coordi.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_x_move = QLineEdit(Form)
        self.lineEdit_x_move.setObjectName(u"lineEdit_x_move")
        self.lineEdit_x_move.setGeometry(QRect(150, 340, 150, 40))
        self.lineEdit_x_move.setFont(font2)
        self.lineEdit_x_move.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_y_move = QLineEdit(Form)
        self.lineEdit_y_move.setObjectName(u"lineEdit_y_move")
        self.lineEdit_y_move.setGeometry(QRect(150, 400, 150, 40))
        self.lineEdit_y_move.setFont(font2)
        self.lineEdit_y_move.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Btn_Quit = QPushButton(Form)
        self.Btn_Quit.setObjectName(u"Btn_Quit")
        self.Btn_Quit.setGeometry(QRect(520, 30, 30, 30))
        self.Btn_Quit.setFont(font)
        self.Btn_Quit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.Btn_Init = QPushButton(Form)
        self.Btn_Init.setObjectName(u"Btn_Init")
        self.Btn_Init.setGeometry(QRect(459, 30, 51, 30))
        self.Btn_Init.setFont(font)
        self.Btn_Init.setLayoutDirection(Qt.LayoutDirection.RightToLeft)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.Btn_FK.setText(QCoreApplication.translate("Form", u"Forward_Kinematics", None))
        self.label.setText(QCoreApplication.translate("Form", u"2AXIS_KINEMATICS", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"THETA1", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"THETA2", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"X_COORDI", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Y_COORDI", None))
        self.Btn_IK.setText(QCoreApplication.translate("Form", u"Inverse_Kinematics", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"X_MOVE", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Y_MOVE", None))
        self.Btn_Pattern.setText(QCoreApplication.translate("Form", u"Pattern_On", None))
        self.lineEdit_theta1.setText(QCoreApplication.translate("Form", u"-45", None))
        self.lineEdit_theta2.setText(QCoreApplication.translate("Form", u"-90", None))
        self.lineEdit_x_coordi.setText(QCoreApplication.translate("Form", u"1.0", None))
        self.lineEdit_y_coordi.setText(QCoreApplication.translate("Form", u"0.0", None))
        self.lineEdit_x_move.setText(QCoreApplication.translate("Form", u"0.1", None))
        self.lineEdit_y_move.setText(QCoreApplication.translate("Form", u"0.0", None))
        self.Btn_Quit.setText(QCoreApplication.translate("Form", u"X", None))
        self.Btn_Init.setText(QCoreApplication.translate("Form", u"Init", None))
    # retranslateUi

